### ISSUE TITLE
app down / 503 Error (Service Unavailable)

### ISSUE THREAD

**Issue by SugarOverflow** [codeforamerica/follow-all#26]
the app is down
error in the console is 503 service unavailable

<img width="775" alt="apperror_followall" src="https://cloud.githubusercontent.com/assets/6685950/12986222/179b4216-d0c4-11e5-807c-53558188c040.png">

**Comment by sferik** [comment]
This is because Heroku changed its pricing and no longer allows for free dynos that run for 24-hours per day. If Code for America would like to sponsor this project, it would only cost $7 per month, but I have no interest in paying that out of pocket.

**Comment by SugarOverflow** [comment]
@sferik Ah, I understand. Thanks for the explanation :)
